#!/bin/bash

# Rotates the screen clockwise from the current position.
# This script assumes that the stylus and screen orientation match.
# (This is a bit of a hack, but I'm letting it be for now.)
device="Wacom Serial Penabled 1FG Touchscreen stylus"
wacomstatus=`xsetwacom get "$device" rotate`

case $wacomstatus in
    "none")
        xsetwacom set "$device" rotate cw
        xrandr -o right ;;
    "cw")
        xsetwacom set "$device" rotate half
        xrandr -o inverted ;;
    "half")
        xsetwacom set "$device" rotate ccw
        xrandr -o left ;;
    "ccw")
        xsetwacom set "$device" rotate none
        xrandr -o normal ;;
    *)
        ;;
esac
