#!/bin/bash

tabletfile="/sys/devices/platform/thinkpad_acpi/hotkey_tablet_mode"
istablet=`cat $tabletfile`

if [ -a "$tabletfile" -a 1 -eq `echo "$istablet"` ]; then
    xrandr -o inverted
    xsetwacom set "Serial Wacom Tablet stylus" rotate half
    xinput set-int-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 8 0 > /dev/null
else
    xrandr -o normal
    xsetwacom set "Serial Wacom Tablet stylus" rotate none
    xinput set-int-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 8 1 > /dev/null
fi
